Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Composition;
using System.Linq;
using System.Threading.Tasks;
using FastReport;
using FastReport.Export.PdfSimple;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ActeAdministratif.Data;
using ActeAdministratif.Models;

namespace ActeAdministratif.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly SNDIContext _context;

        public DocumentsController(SNDIContext context)
        {
            _context = context;
        }
        // Generate File
        public FileResult Generate()
        {
            FastReport.Utils.Config.WebMode = true;
            Report report = new();
            string path = Path.Combine(Directory.GetCurrentDirectory(), "document.frx");
            //var pathServer = Path.Combine(path, "Templates");
            //path = Path.Combine(pathServer, "liste_ordonnance.frx");
            report.Load(path);

            if (report.Report.Prepare())
            {
                PDFSimpleExport pdfExport = new()
                {
                    ShowProgress = false,
                    Subject = "Subject Test",
                    Title = "Report Title"
                };
                MemoryStream ms = new();
                report.Report.Export(pdfExport, ms);
                report.Dispose();
                pdfExport.Dispose();
                ms.Position = 0;
                return File(ms, "application/pdf", "myreport.pdf");
            }

            else
                return null;
        }

     
        



        // GET: Documents
        //public async Task<IActionResult> Index()
        //{
        //      return _context.Document != null ? 
        //                  View(await _context.Document.ToListAsync()) :
        //                  Problem("Entity set 'SNDIContext.Document'  is null.");
        //}

        // GET: Documents second
        public IActionResult Index()
        {
            var enregistrements = _context.Enregistrer
                .Include(e => e.Document) // Charge l'objet Document associé
                .Include(e => e.Filiation) // Charge l'objet Filiation associé
                .ToList();
            return View(enregistrements);
        }

        //Recherche
        public IActionResult Search(string searchNumero)
        {
            var enregistrements = _context.Enregistrer
                .Include(e => e.Document) // Charge l'objet Document associé
                .Include(e => e.Filiation) // Charge l'objet Filiation associé
                .Where(e => e.Document.Numero.Contains(searchNumero))  // Utilisez "==" pour une correspondance exacte
                .ToList();
            return View(enregistrements);
        }


        // GET: Documents/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Document == null)
            {
                return NotFound();
            }

            var document = await _context.Document
                .FirstOrDefaultAsync(m => m.id == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // GET: Documents/Create
        //Recuperer donner de la Bd:
        public IActionResult Create()
        {
            // Récupérez les données des pays depuis votre base de données
            List<Country> countries = _context.T_CONF_COUNTRY.ToList();

            // Vous pouvez trier, filtrer ou manipuler les données ici si nécessaire
            ViewBag.Countries = countries;
            // Transmettez les données des pays à la vue
            ViewBag.Countries = countries;

            return View();
        }

        // POST: Filiations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Numero,Date,Circonscription,LieuxEtablissement,NomDeFamille,NomDeJeuneFille,Prenom,Pseudo,Sexe,SituationMatrimoniale,NombreEnfant,DateDenaissance,LieuxNaissance,PaysNaissance,Nationnalite,CommuneDeNaissance,NumeroDeTelephone,Profession,Domicile,TypeDepiece,NumeroDePiece,DateEdition")] Document document)
        {
            if (ModelState.IsValid)
            {
                _context.Add(document);
                await _context.SaveChangesAsync();

                // Generate the URL for the Details action with the created document ID
                var detailsUrl = Url.Action("Details", new { id = document.id });

                // Redirect to the Details action
                return Redirect(detailsUrl);
            }

            // If ModelState is not valid, return to the Create view
            return View(document);
        }

        // GET: Documents/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Document == null)
            {
                return NotFound();
            }

            var document = await _context.Document.FindAsync(id);
            if (document == null)
            {
                return NotFound();
            }

            List<Country> countries = _context.T_CONF_COUNTRY.ToList();

            // Vous pouvez trier, filtrer ou manipuler les données ici si nécessaire
            ViewBag.Countries = countries;
            // Transmettez les données des pays à la vue
            ViewBag.Countries = countries;

            return View(document);
        }

        // POST: Documents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("id,Numero,Date,Circonscription,LieuxEtablissement,NomDeFamille,NomDeJeuneFille,Prenom,Pseudo,Sexe,SituationMatrimoniale,NombreEnfant,DateDenaissance,LieuxNaissance,PaysNaissance,Nationnalite,CommuneDeNaissance,NumeroDeTelephone,Profession,Domicile,TypeDepiece,NumeroDePiece,DateEdition")] Document document)
        {
            if (id != document.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(document);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DocumentExists(document.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(document);
        }

        // Edit page for 2
        public async Task<IActionResult> Editcmp(string id)
        {
            var enregistrement = await _context.Enregistrer
        .Include(e => e.Document)
        .Include(e => e.Filiation)
        .FirstOrDefaultAsync(e => e.Id == id);

            if (enregistrement == null)
            {
                return NotFound(); // Gérez le cas où l'enregistrement n'est pas trouvé
            }

            return View(enregistrement);
        }

        // POST: Filiations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Editcmp(string id, [Bind("id,NomPere,PrenomPere,DateDenaissancePere,LieuxNaissancePere,NomMere,PrenomMere,DateDenaissanceMere,LieuxNaissanceMere,DocumentId")] Filiation filiation)
        //{
            
        //}

        // GET: Documents/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Document == null)
            {
                return NotFound();
            }

            var document = await _context.Document
                .FirstOrDefaultAsync(m => m.id == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // POST: Documents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Document == null)
            {
                return Problem("Entity set 'SNDIContext.Document'  is null.");
            }
            var document = await _context.Document.FindAsync(id);
            if (document != null)
            {
                _context.Document.Remove(document);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DocumentExists(string id)
        {
          return (_context.Document?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Controllers/HomeController.cs
using ActeAdministratif.Models;
using FastReport.Export.PdfSimple;
using FastReport;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ActeAdministratif.Data;
using Microsoft.EntityFrameworkCore;
using ActeAdministratif.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;



namespace ActeAdministratif.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly SNDIContext _context;
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<SNDIUser> _userManager;

        public HomeController(SNDIContext context, ILogger<HomeController> logger, UserManager<SNDIUser> userManager)
        {
            _logger = logger;
            this._userManager = userManager;
            _context = context;
        }

        public IActionResult Index()
        {
            var enregistrements = _context.Enregistrer
                .Include(e => e.Document) // Charge l'objet Document associé
                .Include(e => e.Filiation) // Charge l'objet Filiation associé
                .ToList();

            int nombreEnregistrements = enregistrements.Count; // Obtenez le nombre d'enregistrements

            ViewBag.NombreEnregistrements = nombreEnregistrements;


            // information demande
            //Status 0
            var informationsDemandes = _context.DemandeInit
               .Include(d => d.Enregistrer)
                   .ThenInclude(e => e.Document)
               .Include(d => d.Enregistrer)
                   .ThenInclude(e => e.Filiation)
               .Where(d => d.status == 0) // Filtrez les DemandesInit avec Status égal à 0
               .ToList();

            int nombreInformationsDemandes = informationsDemandes.Count; // Obtenez le nombre d'InformationDemande

            //Status 1
                    var informationsDemandes1 = _context.DemandeInit
            .Include(d => d.Enregistrer)
                .ThenInclude(e => e.Document)
            .Include(d => d.Enregistrer)
                .ThenInclude(e => e.Filiation)
            .Where(d => d.status == 1) // Filtrez les DemandesInit avec Status égal à 0
            .ToList();

            int nombreInformationsDemandes1 = informationsDemandes1.Count; // Obtenez le nombre d'InformationDemande

            ViewBag.NombreInformationsDemandes1 = nombreInformationsDemandes1; // Ajoutez-le à la ViewBag pour l'afficher dans la vue


            ViewBag.NombreInformationsDemandes = nombreInformationsDemandes;
            return View(enregistrements);
        }


       

        public IActionResult Privacy()
        {
            return View();
        }




        // GET: Documents second
        //public IActionResult Index()
        //{
        //    var enregistrements = _context.Enregistrer
        //        .Include(e => e.Document) // Charge l'objet Document associé
        //        .Include(e => e.Filiation) // Charge l'objet Filiation associé
        //        .ToList();
        //    return View(enregistrements);
        //}




        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
        ////int id
        //public FileResult Generate()
        //{
        //    FastReport.Utils.Config.WebMode = true;
        //    Report report = new();
        //    string path = Path.Combine(Directory.GetCurrentDirectory(), "documents.frx");
        //    //var pathServer = Path.Combine(path, "Templates");
        //    //path = Path.Combine(pathServer, "liste_ordonnance.frx");
        //    report.Load(path);
        //    //report.SetParameterValue("OnerID0",Id)

        //    if (report.Report.Prepare())
        //    {
        //        PDFSimpleExport pdfExport = new()
        //        {
        //            ShowProgress = false,
        //            Subject = "Subject Test",
        //            Title = "Report Title"
        //        };
        //        MemoryStream ms = new();
        //        report.Report.Export(pdfExport, ms);
        //        report.Dispose();
        //        pdfExport.Dispose();
        //        ms.Position = 0;
        //        return File(ms, "application/pdf", "myreport.pdf");
        //    }

        //    else
        //        return null;
        //}
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@{
    Layout = "_Layout"; // Disable the layout for this specific page
}

<style>
    .margin-left-section {
        margin-left: 180px;
    }
</style>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
@*                    <h1 class="m-0">Tableau de bord</h1>*@
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                  
                                <li class="breadcrumb-item active">Tableau de bord</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
    <section class="content content margin-left-section">
            <div class="container-fluid ">
                    <!-- Small boxes (Stat box) -->
                    <div class="row">
                        <div class="col-lg-3 col-6">
                            <!-- small box -->
                            <div class="small-box bg-info">
                                <div class="inner">
                                     <h3>@ViewBag.NombreEnregistrements</h3>                      
                                     <p>Nombres de demandeurs</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-bag"></i>
                                </div>
                               <a asp-controller="Documents"
                                   asp-action="Index" class="small-box-footer">
                            plus info<i class="fa fa-handshake-o"></i>
                        </a>
                      
                            </div>
                        </div>
                        <!-- ./col -->
                        <div class="col-lg-3 col-6">
                            <!-- small box -->
                            <div class="small-box bg-success">
                                <div class="inner">
                            <h3>@ViewBag.NombreInformationsDemandes<sup style="font-size: 20px">%</sup></h3>
                            <p>Nombre de demandes à traiter.</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-stats-bars"></i>
                                </div>
                               <a asp-area="" asp-controller="DemandeInit"
                               asp-action="Index" class="small-box-footer">plus info <i class="fas fa-arrow-circle-right"></i></a>
                            </div>
                        </div>
                        <!-- ./col -->
                      @*  <div class="col-lg-3 col-6">
                            <!-- small box -->
                            <div class="small-box bg-warning">
                                <div class="inner">
                                    <h3>44</h3>

                                    <p>User Registrations</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-person-add"></i>
                                </div>
                                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                            </div>
                        </div>*@
                        <!-- ./col -->
                        <div class="col-lg-3 col-6">
                            <!-- small box -->
                            <div class="small-box bg-danger">
                                <div class="inner">
                            <h3>@ViewBag.NombreInformationsDemandes1</h3>
                            <p>Nombre de demandes traitées</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-pie-graph"></i>
                                </div>
                                <a href="#" class="small-box-footer">plus info <i class="fas fa-arrow-circle-right"></i></a>
                            </div>
                        </div>
                        <!-- ./col -->
                    </div>
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
       